=== cparmor350-source/DTD/factura.dtd
<!ELEMENT factura (fecha, cliente, productos)>
<!ELEMENT fecha (#PCDATA)>

<!ELEMENT cliente (nombre, direccion)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>

<!ELEMENT productos (producto+)>
<!ELEMENT producto (nombre, cantidad, precio)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT precio (#PCDATA)>

=== cparmor350-source/DTD/factura.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE factura SYSTEM "factura.dtd">

<factura>
    <fecha>2026-02-10</fecha>
    <cliente>
        <nombre>Joselito</nombre>
        <direccion>juan sebastian el cano</direccion>
    </cliente>
    <productos>
        <producto>
            <nombre>Teclado</nombre>
            <cantidad>2</cantidad>
            <precio>44,15</precio>
        </producto>
    </productos>
</factura>
